# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lauren Alyssa Ames
email: laurenalyssaames@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Lauren Alyssa Ames is a writer specializing in essays, short stories, humor, and human interest. 
  Her first novel is currently in the works.
baseurl: "/laa-blog" # the subpath of your site, e.g. /blog
url: "https://erchsm.github.io" # the base hostname & protocol for your site
twitter_username: LaurynAymes
instagram_username: laurynaymes

# Build settings
source: src
# markdown: kramdown
# destination: public
