---
title: Lauren Alyssa Ames
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: laurenalyssaames@gmail.com
description: 'Lauren Alyssa Ames is a writer specializing in essays, short stories,
  humor, and human interest.  Her first novel is currently in the works.

'
baseurl: "/laa-blog"
url: https://erchsm.github.io
twitter_username: LaurynAymes
instagram_username: laurynaymes
exclude:
- webpack
- node_modules

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      theme_color: "Ethan"
